main: ${project.mainClass}

name: ${project.name}
description: '${project.description}'
version: '${project.version}'

author: '${project.author}'

commands:
  ringbearer:
    aliases: [lotr]
    # TODO: Better description :D
    description: 'ten.java!'
    usage: None.